/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Mainframe;

import ui.Mainframe.MainJFrame;
import business.DB4OUtil.DB4OUtil;
import business.EcoSystem;
import business.Employee.Employee;
import business.Enterprise.Enterprise;
import business.Enterprise.EnterpriseDirectory;
import business.Network.Network;
import business.Organization.Organization;
import business.Role.CaseReporterRole;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import static java.time.Clock.system;
import java.util.Properties;
import javax.imageio.ImageIO;
import javax.mail.Message;
import javax.mail.Session;
import javax.swing.ImageIcon;
import javax.mail.PasswordAuthentication;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Transport;
import javax.swing.JOptionPane;
/**
 *
 * @author hetal
 */
public class SignUpJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignUpJFrame
     */
   EnterpriseDirectory enterpriseDirectory;
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public SignUpJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        this.setSize(1080, 680);
        this.setExtendedState(MainJFrame.MAXIMIZED_BOTH);
        populateNetworkComboBox();
       // emailValidator();
    }
 private void populateNetworkComboBox(){
        cb_city.removeAllItems();
        
        for (Network network : system.getNetworkList()){
            cb_city.addItem(network);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Back = new javax.swing.JButton();
        detailsjPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fnamejLabel = new javax.swing.JLabel();
        contactjLabel = new javax.swing.JLabel();
        usernamejLabel = new javax.swing.JLabel();
        passwordjLabel = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_phoneNo = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        bt_signUp = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        cb_city = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_Back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailsjPanel.setBackground(new java.awt.Color(204, 204, 255));
        detailsjPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTER YOUR DETAILS HERE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 142, 0, 0);
        detailsjPanel.add(jLabel1, gridBagConstraints);

        fnamejLabel.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        fnamejLabel.setForeground(new java.awt.Color(0, 0, 204));
        fnamejLabel.setText("NAME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 142, 0, 0);
        detailsjPanel.add(fnamejLabel, gridBagConstraints);

        contactjLabel.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        contactjLabel.setForeground(new java.awt.Color(0, 0, 204));
        contactjLabel.setText("PHONE NUMBER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 142, 0, 0);
        detailsjPanel.add(contactjLabel, gridBagConstraints);

        usernamejLabel.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        usernamejLabel.setForeground(new java.awt.Color(0, 0, 204));
        usernamejLabel.setText("USERNAME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 142, 0, 0);
        detailsjPanel.add(usernamejLabel, gridBagConstraints);

        passwordjLabel.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        passwordjLabel.setForeground(new java.awt.Color(0, 0, 204));
        passwordjLabel.setText("PASSWORD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 142, 0, 0);
        detailsjPanel.add(passwordjLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 27, 0, 0);
        detailsjPanel.add(txt_name, gridBagConstraints);

        txt_phoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneNoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 27, 0, 0);
        detailsjPanel.add(txt_phoneNo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 27, 0, 0);
        detailsjPanel.add(txt_username, gridBagConstraints);

        bt_signUp.setBackground(new java.awt.Color(0, 0, 204));
        bt_signUp.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        bt_signUp.setForeground(java.awt.Color.white);
        bt_signUp.setText("SIGN UP");
        bt_signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_signUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_signUpMouseExited(evt);
            }
        });
        bt_signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_signUpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 51, 20, 0);
        detailsjPanel.add(bt_signUp, gridBagConstraints);

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 27, 0, 0);
        detailsjPanel.add(txt_password, gridBagConstraints);

        cb_city.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_cityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 27, 0, 0);
        detailsjPanel.add(cb_city, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("CITY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 142, 0, 0);
        detailsjPanel.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 106);
        detailsjPanel.add(jLabel3, gridBagConstraints);

        bt_Back.setBackground(new java.awt.Color(0, 0, 204));
        bt_Back.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        bt_Back.setForeground(new java.awt.Color(255, 255, 255));
        bt_Back.setText("BACK");
        bt_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BackActionPerformed(evt);
            }
        });
        detailsjPanel.add(bt_Back, new java.awt.GridBagConstraints());

        getContentPane().add(detailsjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1380, 560));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 826, -1));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Songti SC", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("COMPLAINANT DETAILS");
        jButton1.setToolTipText("");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_signUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_signUpMouseEntered
        bt_signUp.setForeground(Color.WHITE);
    }//GEN-LAST:event_bt_signUpMouseEntered

    private void bt_signUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_signUpMouseExited
        bt_signUp.setForeground(Color.BLACK);
    }//GEN-LAST:event_bt_signUpMouseExited

    private void bt_signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_signUpActionPerformed

        if(txt_name.getText().isEmpty() || txt_phoneNo.getText().isEmpty() ||
            "ssgetText()".isEmpty() || txt_username.getText().isEmpty() ||
            txt_password.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill all details", "Info", JOptionPane.INFORMATION_MESSAGE);
        }else{

            Network network = (Network) cb_city.getSelectedItem();

            String username = txt_username.getText();
            String password = String.valueOf(txt_password.getPassword());
            String name = txt_name.getText();
            String contactno=txt_phoneNo.getText();
            //long contact=Long.parseLong(contactno);
         //   String email="aaa@gmail.com";

            if(isNumber(contactno)){
                // JOptionPane.showMessageDialog(null, "Info added!", "Info", JOptionPane.INFORMATION_MESSAGE);
                long contact = Long.parseLong(contactno);

            }
            else{
                JOptionPane.showMessageDialog(null, "Contact should be a number!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }

            int length= contactno.length();
            if(length<10||length>10)
            {
                txt_phoneNo.setEditable(true);
                JOptionPane.showMessageDialog(null, "Contact should be 10 digits!", "Warning", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            else
            {
                txt_phoneNo.setEditable(false);

            }

            String validate="^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
//            if(1==0)
//            {
//                JOptionPane.showMessageDialog(null, "Please enter valid email");
//                return;
//            }
            System.out.println("start1");
            boolean x = true;

            if(network.getEnterpriseDirectory().searchEnterprisebyType(Enterprise.EnterpriseType.CaseReporter)==null){
                x=false;
            }

            if(x==true){
                Enterprise enterprise = network.getEnterpriseDirectory().searchEnterprisebyType(Enterprise.EnterpriseType.CaseReporter);
                System.out.println("start2");
                if(enterprise.getOrganizationDirectory().searchOrganizationbyname("CaseReporterOrganization")==null){
                    System.out.println("start3");
                    Organization.Type type = (Organization.Type) Organization.Type.CaseReporter;
                    Organization org= enterprise.getOrganizationDirectory().createOrganization(type);
                    Employee employee= org.getEmployeeDirectory().createEmployee(name);
                }
                else{
                    System.out.println("start4");

                    Organization org = enterprise.getOrganizationDirectory().searchOrganizationbyname("CaseReporterOrganization");
                    Employee employee= org.getEmployeeDirectory().createEmployee(name);
                    if(org.getUserAccountDirectory().CheckIsValidInput(password)){
                        UserAccount userAccount=org.getUserAccountDirectory().createUserAccnt(username, password, employee, new CaseReporterRole());
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Password should have a minimum length of 8 and contain atleast 1 Uppercase, 1 Lowercase, 1 Special character and 1 Digit ");
                        txt_password.setText("");
                        return;
                    }
                }
            }
            else{
                Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise("HS", Enterprise.EnterpriseType.CaseReporter);
                if(enterprise.getOrganizationDirectory().searchOrganizationbyname("CaseReporterOrganization")==null){
                    System.out.println("start3");
                    Organization.Type type = (Organization.Type) Organization.Type.CaseReporter;
                    Organization org= enterprise.getOrganizationDirectory().createOrganization(type);
                    Employee employee= org.getEmployeeDirectory().createEmployee(name);
                    if(org.getUserAccountDirectory().CheckIsValidInput(password)){
                        UserAccount userAccount=org.getUserAccountDirectory().createUserAccnt(username, password, employee, new CaseReporterRole());
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Password should have a minimum length of 8 and contain atleast 1 Uppercase, 1 Lowercase, 1 Special character and 1 Digit ");
                        txt_password.setText("");
                        return;
                    }

                }
                else{
                    //System.out.println("start4");
                    Organization org = enterprise.getOrganizationDirectory().searchOrganizationbyname("CaseReporterOrganization");
                    Employee employee= org.getEmployeeDirectory().createEmployee(name);
                    if(org.getUserAccountDirectory().CheckIsValidInput(password)){
                        UserAccount userAccount=org.getUserAccountDirectory().createUserAccnt(username, password, employee, new CaseReporterRole());
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Password should have a minimum length of 8 and contain atleast 1 Uppercase, 1 Lowercase, 1 Special character and 1 Digit ");
                        txt_password.setText("");
                        return;
                    }
                }
            }


            this.setVisible(false);
            Enterprise enterprise = network.getEnterpriseDirectory().searchEnterprisebyType(Enterprise.EnterpriseType.CaseReporter);
            Organization org = enterprise.getOrganizationDirectory().searchOrganizationbyname("CaseReporterOrganization");
            UserAccount ua= org.getUserAccountDirectory().authenticateUserAccnt(username, password);
            //ReportJFrame r = new ReportJFrame(system,network,ua,org);
            dB4OUtil.storeSystem(system);
            SignInJFrame s = new SignInJFrame();
            s.setVisible(true);
        }

    }//GEN-LAST:event_bt_signUpActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void cb_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_cityActionPerformed

    }//GEN-LAST:event_cb_cityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        MainJFrame eng = new MainJFrame();
        eng.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_phoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneNoActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_BackActionPerformed

    private void bt_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BackActionPerformed
        // TODO add your handling code here:
         dB4OUtil.storeSystem(system);
            MainJFrame s = new MainJFrame();
            s.setVisible(true);
    }//GEN-LAST:event_bt_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpJFrame().setVisible(true);
            }
        });
    }

    
public static boolean isNumber(String price){
        try{
            Long.parseLong(price);
            return true;    
        }
        catch(Exception e)
        {
             return false;
        }  
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton bt_Back;
    private javax.swing.JButton bt_signUp;
    private javax.swing.JComboBox cb_city;
    private javax.swing.JLabel contactjLabel;
    private javax.swing.JPanel detailsjPanel;
    private javax.swing.JLabel fnamejLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel passwordjLabel;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_phoneNo;
    private javax.swing.JTextField txt_username;
    private javax.swing.JLabel usernamejLabel;
    // End of variables declaration//GEN-END:variables
}
