/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Mainframe;

//import ui.Mainframe.SignInJFrame;

import business.EcoSystem;
import business.DB4OUtil.DB4OUtil;
import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author hetal
 */
public class SignInJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignInJFrame
     */
   private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public SignInJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        this.setSize(1080, 680);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setDividerLocation(230);
        this.setExtendedState(SignInJFrame.MAXIMIZED_BOTH);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        UsernamejLabel = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        PasswordjLabel = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        bt_SignIn = new javax.swing.JButton();
        bt_SignOut = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernamejLabel.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        UsernamejLabel.setForeground(new java.awt.Color(0, 0, 204));
        UsernamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsernamejLabel.setText("USERNAME");
        jPanel1.add(UsernamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 140, 22));

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 78, 140, 30));

        PasswordjLabel.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        PasswordjLabel.setForeground(new java.awt.Color(0, 0, 204));
        PasswordjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordjLabel.setText("PASSWORD");
        jPanel1.add(PasswordjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 21));

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 140, 30));

        bt_SignIn.setBackground(new java.awt.Color(0, 0, 204));
        bt_SignIn.setFont(new java.awt.Font("Songti SC", 1, 14)); // NOI18N
        bt_SignIn.setForeground(new java.awt.Color(255, 255, 255));
        bt_SignIn.setText("SIGN IN");
        bt_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SignInActionPerformed(evt);
            }
        });
        jPanel1.add(bt_SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 110, 30));

        bt_SignOut.setBackground(new java.awt.Color(0, 0, 204));
        bt_SignOut.setFont(new java.awt.Font("Songti SC", 1, 14)); // NOI18N
        bt_SignOut.setForeground(new java.awt.Color(255, 255, 255));
        bt_SignOut.setText("SIGN OUT");
        bt_SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SignOutActionPerformed(evt);
            }
        });
        jPanel1.add(bt_SignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 110, 30));

        bt_back.setBackground(new java.awt.Color(0, 0, 204));
        bt_back.setFont(new java.awt.Font("Songti SC", 1, 14)); // NOI18N
        bt_back.setForeground(new java.awt.Color(255, 255, 255));
        bt_back.setText("BACK");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });
        jPanel1.add(bt_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 110, 30));

        jSplitPane1.setLeftComponent(jPanel1);

        container.setBackground(new java.awt.Color(244, 241, 222));
        container.setMinimumSize(new java.awt.Dimension(200, 100));
        container.setLayout(new java.awt.CardLayout());

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Monaco", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(61, 64, 91));
        jButton1.setText("Women Abuse Help");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        container.add(jButton1, "card2");

        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 51, 1420, 640));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 1, 1420, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void bt_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SignInActionPerformed
        // TODO add your handling code here:

        String userName = txt_username.getText();
        // Get Password
        char[] passwordCharArray = txt_password.getPassword();
        String password = String.valueOf(passwordCharArray);

        //Step1: Check in the system admin user account directory if you have the user
        UserAccount userAccount=system.getUserAccountDirectory().authenticateUserAccnt(userName, password);

        Enterprise inEnterprise=null;
        Organization inOrganization=null;
        Network innetwork = null;

        if(userAccount==null){
            //Step 2: Go inside each network and check each enterprise
            for(Network network:system.getNetworkList()){
                //Step 2.a: check against each enterprise
                for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                    userAccount=enterprise.getUserAccountDirectory().authenticateUserAccnt(userName, password);
                    if(userAccount==null){
                        //Step 3:check against each organization for each enterprise
                        for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                            userAccount=organization.getUserAccountDirectory().authenticateUserAccnt(userName, password);
                            if(userAccount!=null){
                                inEnterprise=enterprise;
                                inOrganization=organization;
                                innetwork = network;
                                break;
                            }
                        }

                    }
                    else{
                        inEnterprise=enterprise;
                        break;
                    }
                    if(inOrganization!=null){
                        break;
                    }
                }
                if(inEnterprise!=null){
                    break;
                }
            }
        }

        if(userAccount==null){
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }
        else{
            CardLayout layout=(CardLayout)container.getLayout();
            container.add("workArea",userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEnterprise, system,innetwork));
            layout.next(container);
        }

        bt_SignIn.setEnabled(false);
        bt_SignOut.setEnabled(true);
        txt_username.setEnabled(false);
        txt_password.setEnabled(false);
    }//GEN-LAST:event_bt_SignInActionPerformed

    private void bt_SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SignOutActionPerformed
        // TODO add your handling code here:
        bt_SignOut.setEnabled(false);
        txt_username.setEnabled(true);
        txt_password.setEnabled(true);
        bt_SignIn.setEnabled(true);

        txt_username.setText("");
        txt_password.setText("");

        container.removeAll();
////        SigninPageImgJpanel blankJP = new SigninPageImgJpanel();
//        container.add("blank", blankJP);
//        CardLayout crdLyt = (CardLayout) container.getLayout();
        //crdLyt.next(container);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_bt_SignOutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        MainJFrame engi = new MainJFrame();
        engi.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        // TODO add your handling code here:
        dB4OUtil.storeSystem(system);
            MainJFrame s = new MainJFrame();
            s.setVisible(true);
    }//GEN-LAST:event_bt_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PasswordjLabel;
    private javax.swing.JLabel UsernamejLabel;
    private javax.swing.JButton bt_SignIn;
    private javax.swing.JButton bt_SignOut;
    private javax.swing.JButton bt_back;
    private javax.swing.JPanel container;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
