/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Hospital;

/**
 *
 * @author heenashah
 */
public class DoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorJPanel
     */
    public DoctorJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        DoctorTopJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DoctorBottomJPanel = new javax.swing.JPanel();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel1.setFont(new java.awt.Font("Songti SC", 1, 28)); // NOI18N
        jLabel1.setText("WELCOME DOCTOR");

        javax.swing.GroupLayout DoctorTopJPanelLayout = new javax.swing.GroupLayout(DoctorTopJPanel);
        DoctorTopJPanel.setLayout(DoctorTopJPanelLayout);
        DoctorTopJPanelLayout.setHorizontalGroup(
            DoctorTopJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< Updated upstream
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoctorTopJPanelLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(219, 219, 219))
=======
            .addGroup(DoctorTopJPanelLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1)
                .addContainerGap(179, Short.MAX_VALUE))
>>>>>>> Stashed changes
        );
        DoctorTopJPanelLayout.setVerticalGroup(
            DoctorTopJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoctorTopJPanelLayout.createSequentialGroup()
<<<<<<< Updated upstream
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
=======
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
>>>>>>> Stashed changes
        );

        jSplitPane1.setTopComponent(DoctorTopJPanel);

        javax.swing.GroupLayout DoctorBottomJPanelLayout = new javax.swing.GroupLayout(DoctorBottomJPanel);
        DoctorBottomJPanel.setLayout(DoctorBottomJPanelLayout);
        DoctorBottomJPanelLayout.setHorizontalGroup(
            DoctorBottomJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< Updated upstream
            .addGap(0, 720, Short.MAX_VALUE)
        );
        DoctorBottomJPanelLayout.setVerticalGroup(
            DoctorBottomJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
=======
            .addGap(0, 628, Short.MAX_VALUE)
        );
        DoctorBottomJPanelLayout.setVerticalGroup(
            DoctorBottomJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
>>>>>>> Stashed changes
        );

        jSplitPane1.setRightComponent(DoctorBottomJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< Updated upstream
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
=======
            .addComponent(jSplitPane1)
>>>>>>> Stashed changes
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DoctorBottomJPanel;
    private javax.swing.JPanel DoctorTopJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
