/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Hospital;

import business.EcoSystem;
import business.WorkQueue.Medicines;
import business.WorkQueue.PharmacistWorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author heenashah
 */
public class PrescribeMedicinesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrescribeMedicinesJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    PharmacistWorkRequest pRequest;
    public PrescribeMedicinesJPanel(JPanel userProcessContainer, EcoSystem system,PharmacistWorkRequest pRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.pRequest = pRequest;
        populatereport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_DName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_particulars = new javax.swing.JTable();
        bt_ReqPharm = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_PName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Particulars = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_qty = new javax.swing.JTextField();
        bt_add = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setForeground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Songti SC", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRESCRIPTION");
        jLabel1.setAutoscrolls(true);

        jLabel2.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Doctor's Name:");
        jLabel2.setAutoscrolls(true);

        txt_DName.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Date:");
        jLabel3.setAutoscrolls(true);

        txt_date.setEnabled(false);

        jScrollPane1.setAutoscrolls(true);

        tb_particulars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Particulars", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(tb_particulars);

        bt_ReqPharm.setFont(new java.awt.Font("Songti SC", 1, 14)); // NOI18N
        bt_ReqPharm.setForeground(new java.awt.Color(0, 0, 204));
        bt_ReqPharm.setText("REQUEST PHARMACIST");
        bt_ReqPharm.setAutoscrolls(true);
        bt_ReqPharm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_ReqPharmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_ReqPharmMouseExited(evt);
            }
        });
        bt_ReqPharm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ReqPharmActionPerformed(evt);
            }
        });

        bt_back.setFont(new java.awt.Font("Songti SC", 1, 14)); // NOI18N
        bt_back.setForeground(new java.awt.Color(0, 0, 204));
        bt_back.setText("BACK");
        bt_back.setAutoscrolls(true);
        bt_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_backMouseExited(evt);
            }
        });
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Patient Name:");
        jLabel5.setAutoscrolls(true);

        txt_PName.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Particulars:");
        jLabel6.setAutoscrolls(true);

        txt_Particulars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ParticularsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Quantity:");
        jLabel4.setAutoscrolls(true);

        txt_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qtyActionPerformed(evt);
            }
        });

        bt_add.setFont(new java.awt.Font("Songti SC", 1, 14)); // NOI18N
        bt_add.setForeground(new java.awt.Color(0, 0, 204));
        bt_add.setText("ADD");
        bt_add.setAutoscrolls(true);
        bt_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_addMouseExited(evt);
            }
        });
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(bt_back)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_add)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_Particulars, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txt_DName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_PName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_qty))))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_ReqPharm)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bt_back)
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_PName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_DName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_Particulars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addGap(80, 80, 80)
                .addComponent(bt_ReqPharm)
                .addGap(85, 85, 85))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ReqPharmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ReqPharmMouseEntered
          bt_ReqPharm.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ReqPharmMouseEntered

    private void bt_ReqPharmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ReqPharmMouseExited
          bt_ReqPharm.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ReqPharmMouseExited

    private void bt_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_backMouseEntered
           bt_back.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_bt_backMouseEntered

    private void bt_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_backMouseExited
           bt_back.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_backMouseExited

    private void bt_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_addMouseEntered

    private void bt_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_addMouseExited

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:
        Medicines M = new Medicines(txt_Particulars.getText(),Integer.parseInt(txt_qty.getText()));
        pRequest.getMedicines().add(M);
        populatetable();
        txt_qty.setText("");
        txt_Particulars.setText("");
    }//GEN-LAST:event_bt_addActionPerformed

    private void txt_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qtyActionPerformed

    private void bt_ReqPharmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ReqPharmActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Request submitted to Pharmacy Department.");
    }//GEN-LAST:event_bt_ReqPharmActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //CaseRequestJPanel sysAdminwjp = (CaseRequestJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_bt_backActionPerformed

    private void txt_ParticularsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ParticularsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ParticularsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ReqPharm;
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_particulars;
    private javax.swing.JTextField txt_DName;
    private javax.swing.JTextField txt_PName;
    private javax.swing.JTextField txt_Particulars;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_qty;
    // End of variables declaration//GEN-END:variables

    private void populatereport() {
        Date date = new Date();
        pRequest.setRequestDate(date);
        txt_date.setText(date.toString());
        txt_DName.setText(pRequest.getSender().toString());
        txt_PName.setText(pRequest.getDoctorWorkRequest().getCaseReporterWorkRequest().getUserName());
        populatetable();
        
    }

    private void populatetable() {
        DefaultTableModel model= (DefaultTableModel) tb_particulars.getModel();
        Object[] row=new Object[2];
        model.setRowCount(0);
        
         for(Medicines M : pRequest.getMedicines())
         {
         
            row[0]=M;
            row[1]=M.getAmount();
            
            model.addRow(row);
            
        }
    }
}
