/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Hospital;

import business.EcoSystem;
import business.Network.Network;
import business.UserAccount.UserAccount;
import business.WorkQueue.LabAssistantWorkRequest;
import business.WorkQueue.LabTest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author heenashah
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestLabTestJPanel
     */
    //userProcessContainer,system,labrequest,userAccount,network
    JPanel userProcessContainer;
    EcoSystem system;
    LabAssistantWorkRequest labrequest;
    UserAccount userAccount;
    Network network;
    public RequestLabTestJPanel(JPanel userProcessContainer, EcoSystem system,LabAssistantWorkRequest labrequest,UserAccount userAccount,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.labrequest = labrequest;
        this.userAccount = userAccount;
        this.network = network;
        
        populateform();
        populatetable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_PName = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        bt_ReqTest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_tests = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_DName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_TestName = new javax.swing.JTextField();
        bt_AddTest = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Songti SC", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REQUEST LAB TEST");

        jLabel2.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("PATIENT'S NAME");

        jLabel3.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("DATE");

        txt_PName.setEnabled(false);

        txt_date.setEnabled(false);

        bt_ReqTest.setBackground(new java.awt.Color(0, 0, 204));
        bt_ReqTest.setFont(new java.awt.Font("Songti SC", 1, 14)); // NOI18N
        bt_ReqTest.setForeground(new java.awt.Color(255, 255, 255));
        bt_ReqTest.setText("REQUEST LAB TEST");
        bt_ReqTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_ReqTestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_ReqTestMouseExited(evt);
            }
        });
        bt_ReqTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ReqTestActionPerformed(evt);
            }
        });

        tb_tests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Test(s)"
            }
        ));
        tb_tests.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tb_tests);

        jLabel4.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("DOCTOR'S NAME");

        txt_DName.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("TEST NAME");

        bt_AddTest.setBackground(new java.awt.Color(0, 0, 204));
        bt_AddTest.setFont(new java.awt.Font("Songti SC", 1, 14)); // NOI18N
        bt_AddTest.setForeground(new java.awt.Color(255, 255, 255));
        bt_AddTest.setText("ADD TEST");
        bt_AddTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_AddTestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_AddTestMouseExited(evt);
            }
        });
        bt_AddTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AddTestActionPerformed(evt);
            }
        });

        bt_back.setBackground(new java.awt.Color(0, 0, 204));
        bt_back.setFont(new java.awt.Font("Songti SC", 1, 14)); // NOI18N
        bt_back.setForeground(new java.awt.Color(255, 255, 255));
        bt_back.setText("BACK");
        bt_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_backMouseExited(evt);
            }
        });
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_TestName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txt_DName)
                                    .addComponent(txt_PName)))
                            .addComponent(bt_AddTest))
                        .addGap(115, 115, 115)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 291, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_ReqTest)
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(bt_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_back)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addGap(99, 99, 99)
                        .addComponent(bt_ReqTest)
                        .addGap(117, 117, 117))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_PName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addComponent(txt_DName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txt_TestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bt_AddTest)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ReqTestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ReqTestMouseEntered
           bt_ReqTest.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ReqTestMouseEntered

    private void bt_ReqTestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ReqTestMouseExited
       bt_ReqTest.setForeground(Color.BLACK);   // TODO add your handling code here:
    }//GEN-LAST:event_bt_ReqTestMouseExited

    private void bt_ReqTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ReqTestActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Request submitted to Forensic Department.");    
    }//GEN-LAST:event_bt_ReqTestActionPerformed

    private void bt_AddTestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AddTestMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_AddTestMouseEntered

    private void bt_AddTestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AddTestMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_AddTestMouseExited

    private void bt_AddTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AddTestActionPerformed
        // TODO add your handling code here:
        LabTest Lt = new LabTest(txt_TestName.getText());
        Lt.setResult("Waiting");
        labrequest.getLabTestList().add(Lt);
        populatetable();
        txt_TestName.setText("");
        
        
    }//GEN-LAST:event_bt_AddTestActionPerformed

    private void bt_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_backMouseEntered
        bt_back.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_bt_backMouseEntered

    private void bt_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_backMouseExited
        bt_back.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_backMouseExited

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //CaseRequestJPanel sysAdminwjp = (CaseRequestJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_bt_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_AddTest;
    private javax.swing.JButton bt_ReqTest;
    private javax.swing.JButton bt_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_tests;
    private javax.swing.JTextField txt_DName;
    private javax.swing.JTextField txt_PName;
    private javax.swing.JTextField txt_TestName;
    private javax.swing.JTextField txt_date;
    // End of variables declaration//GEN-END:variables

    private void populateform() {
        txt_DName.setText(labrequest.getSender().toString());
        txt_PName.setText(labrequest.getDoctorWorkRequest().getCaseReporterWorkRequest().getUserName());
        Date date = new Date();
        txt_date.setText(date.toString());
        
    }

    private void populatetable() {
        DefaultTableModel model= (DefaultTableModel) tb_tests.getModel();
        Object[] row=new Object[1];
        model.setRowCount(0);
        
         for(LabTest LT : labrequest.getLabTestList())
         {
         
            row[0]=LT;
            
            model.addRow(row);
        }
        
    }
}
