/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CaseVolunteer;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.CaseVolunteerOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;

import javax.swing.JPanel;

/**
 *
 * @author hetal
 */
public class CaseVolunteerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CaseVolunteerJPanel
     */
     private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private CaseVolunteerOrganization CVOrg; 
 //   private NGOrgEnterprise NGOrgenterprise;
    private Network network;
    public CaseVolunteerJPanel(JPanel userProcessContainer, UserAccount account, Organization CVOrg,Enterprise enterprise,EcoSystem business,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.CVOrg = (CaseVolunteerOrganization)CVOrg;
        this.network = network;
        popBtm();
        CaseVolunteerSplitJPanel.setDividerSize(0);
        CaseVolunteerSplitJPanel.setDividerLocation(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        CaseVolunteerSplitJPanel = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        lblUpperPart = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        jPanel1.setLayout(new java.awt.BorderLayout());

        CaseVolunteerSplitJPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setForeground(new java.awt.Color(61, 64, 91));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblUpperPart.setFont(new java.awt.Font("Songti SC", 1, 28)); // NOI18N
        lblUpperPart.setForeground(new java.awt.Color(0, 0, 204));
        lblUpperPart.setText("WELCOME CASE VOLUNTEER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 98, 43, 108);
        jPanel2.add(lblUpperPart, gridBagConstraints);

        CaseVolunteerSplitJPanel.setTopComponent(jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());
        CaseVolunteerSplitJPanel.setRightComponent(jPanel3);

        jPanel1.add(CaseVolunteerSplitJPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane CaseVolunteerSplitJPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblUpperPart;
    // End of variables declaration//GEN-END:variables
 
    private void popBtm() {
        CaseRequestJPanel caserequestJPanel=new CaseRequestJPanel(userProcessContainer,business,CVOrg,userAccount,network);
        System.out.println("CaseManagerJPanel"+userAccount.getUsername()+userAccount.getPwd());
        CaseVolunteerSplitJPanel.setBottomComponent(caserequestJPanel);
    }



}
