/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Lab;

import business.EcoSystem;
import business.Enterprise.WellnessEnterprise;
import business.Network.Network;
import business.Organization.ForensicOrganization;
import business.UserAccount.UserAccount;
import business.WorkQueue.LabAssistantWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hetal
 */
public class LabRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabRequestJPanel
     */
    /**
     * Creates new form LabRequestJPanel
     */
     JPanel userProcessContainer;
    EcoSystem system;
    //userProcessContainer,business,network,Henterprise,userAccount
    Network network;
    WellnessEnterprise enterprise;
    UserAccount userAccount;
    ForensicOrganization Organization;
    public LabRequestJPanel(JPanel userProcessContainer, EcoSystem system, Network network, WellnessEnterprise enterprise, UserAccount userAccount,ForensicOrganization Organization ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.enterprise = enterprise;
        this.network = network;
        this.userAccount = userAccount;
        this.Organization = Organization;
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ManageLab = new javax.swing.JTable();
        bt_Assign = new javax.swing.JButton();
        bt_View = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Requests");

        tb_ManageLab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Doctor's Name", "Patient's Name", "LabStatus", "Lab Assistant Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_ManageLab);

        bt_Assign.setBackground(new java.awt.Color(0, 0, 204));
        bt_Assign.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_Assign.setForeground(new java.awt.Color(255, 255, 255));
        bt_Assign.setText("Assign Request");
        bt_Assign.setBorderPainted(false);
        bt_Assign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_AssignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_AssignMouseExited(evt);
            }
        });
        bt_Assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AssignActionPerformed(evt);
            }
        });

        bt_View.setBackground(new java.awt.Color(0, 0, 204));
        bt_View.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_View.setForeground(new java.awt.Color(255, 255, 255));
        bt_View.setText("View Request");
        bt_View.setBorderPainted(false);
        bt_View.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ViewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_ViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_ViewMouseExited(evt);
            }
        });
        bt_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_Assign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_View)))
                .addGap(109, 109, 109))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Assign)
                    .addComponent(bt_View))
                .addGap(142, 142, 142))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_AssignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AssignMouseEntered
        bt_Assign.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_bt_AssignMouseEntered

    private void bt_AssignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AssignMouseExited
        bt_Assign.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_AssignMouseExited

    private void bt_AssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tb_ManageLab.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        WorkRequest request = (LabAssistantWorkRequest)tb_ManageLab.getValueAt(selectedRow, 2);
        request.setReceiver(userAccount);
        request.setStatus("Accepted");
        populateTable();
    }//GEN-LAST:event_bt_AssignActionPerformed

    private void bt_ViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ViewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ViewMouseClicked

    private void bt_ViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ViewMouseEntered
        bt_View.setForeground(new Color(0,128,128));            // TODO add your handling code here:
    }//GEN-LAST:event_bt_ViewMouseEntered

    private void bt_ViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ViewMouseExited
        bt_Assign.setForeground(Color.black);         // TODO add your handling code here:
    }//GEN-LAST:event_bt_ViewMouseExited

    private void bt_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tb_ManageLab.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        LabAssistantWorkRequest request = (LabAssistantWorkRequest)tb_ManageLab.getValueAt(selectedRow, 2);

        if (request.getReceiver()!=userAccount){
            JOptionPane.showMessageDialog(this, "You cannot view the report of this case. Access Denied.");
        }else{

            TestResultsJPanel caseReportJPanel = new TestResultsJPanel(userProcessContainer,system,request);
            userProcessContainer.add("caseReportJPanel", caseReportJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        }
    }//GEN-LAST:event_bt_ViewActionPerformed
private void populateTable() {
        
        DefaultTableModel model= (DefaultTableModel) tb_ManageLab.getModel();
        Object[] row=new Object[4];
        model.setRowCount(0);
        
        
         for(LabAssistantWorkRequest request : Organization.getWorkQueue().getLabAssistanceWorkRequest())
         {
         
            row[0]=request.getDoctorWorkRequest().getReceiver();
            row[1] = request.getDoctorWorkRequest().getCaseReporterWorkRequest().getUserName();
            row[2] = request;
            if (request.getReceiver()==null){
                row[3] = "Not Assigned";
            }else{
                row[3] = request.getReceiver();
            }
            
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Assign;
    private javax.swing.JButton bt_View;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_ManageLab;
    // End of variables declaration//GEN-END:variables
}
