/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.sysadmin;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.CaseVolunteerOrganization;
import business.Organization.Organization;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author heenashah
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    private HashMap<String, Integer> chart;
    int bostoncases,seattlecases;
   
    private HashMap<String, Integer> piechartsea;
    
    /**
     * Creates new form ManageNetworkJPanel
     */
    public ManageNetworkJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        chart= new HashMap<String,Integer>();
        //piechartbos=new HashMap<String,Integer>();
        piechartsea=new HashMap<String,Integer>();

        populateNetworkTable();
    }
    
    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) tb_network.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network;
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        bt_add = new javax.swing.JButton();
        bt_remove = new javax.swing.JButton();
        bt_report = new javax.swing.JButton();
        bt_viewcases = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_network = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setBackground(new java.awt.Color(51, 153, 255));
        jLabel1.setFont(new java.awt.Font("Songti SC", 1, 28)); // NOI18N
        jLabel1.setText("MANAGE NETWORKS");

        jLabel2.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        jLabel2.setText("NETWORK NAME");

        bt_add.setBackground(new java.awt.Color(51, 102, 255));
        bt_add.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        bt_add.setForeground(new java.awt.Color(255, 255, 255));
        bt_add.setText("ADD");
        bt_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_addMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_addMouseEntered(evt);
            }
        });
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        bt_remove.setBackground(new java.awt.Color(51, 102, 255));
        bt_remove.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        bt_remove.setForeground(new java.awt.Color(255, 255, 255));
        bt_remove.setText("REMOVE");
        bt_remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_removeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_removeMouseEntered(evt);
            }
        });
        bt_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_removeActionPerformed(evt);
            }
        });

        bt_report.setBackground(new java.awt.Color(51, 102, 255));
        bt_report.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        bt_report.setForeground(new java.awt.Color(255, 255, 255));
        bt_report.setText("REPORT");
        bt_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reportActionPerformed(evt);
            }
        });

        bt_viewcases.setBackground(new java.awt.Color(51, 102, 255));
        bt_viewcases.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        bt_viewcases.setForeground(new java.awt.Color(255, 255, 255));
        bt_viewcases.setText("VIEW CASES");
        bt_viewcases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_viewcasesActionPerformed(evt);
            }
        });

        tb_network.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "NETWORK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_network);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(bt_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(bt_report, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(bt_viewcases)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48)
                        .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Name))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_report, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_viewcases, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addMouseExited
        bt_add.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_addMouseExited

    private void bt_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addMouseEntered
        bt_add.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_bt_addMouseEntered

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:

        if( txt_Name.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "please enter all mandatory fields");
            return;
        }
        String name = txt_Name.getText();

        Network network = system.createAndAddNetwork();
        network.setNameOfNetwork(name);

        populateNetworkTable();
        txt_Name.setText("");
    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_removeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_removeMouseExited
        bt_remove.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_removeMouseExited

    private void bt_removeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_removeMouseEntered
        bt_remove.setForeground(new Color(0,128,128));// TODO add your handling code here:
    }//GEN-LAST:event_bt_removeMouseEntered

    private void bt_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_removeActionPerformed
        // TODO add your handling code here:

        int selectedRow = tb_network.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select the row to delete the account", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{

            Network p=(Network) tb_network.getValueAt(selectedRow, 0);

            for (Network network : system.getNetworkList()) {
                if(p==network){
                    system.getNetworkList().remove(p);
                    break;
                }
            }
            JOptionPane.showMessageDialog(null, "You have successfully deleted the account");
            populateNetworkTable();
        }
    }//GEN-LAST:event_bt_removeActionPerformed

    private void bt_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reportActionPerformed

        int selectedRow = tb_network.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please choose a network");
            return;
        }
        Network network= (Network) tb_network.getValueAt(selectedRow, 0);
        Enterprise e= network.getEnterpriseDirectory().searchEnterprisebyType(Enterprise.EnterpriseType.NGO);

        for (Organization o: e.getOrganizationDirectory().getOrganizationList())
        {   Organization org=null;

            if(o instanceof CaseVolunteerOrganization)
            {
                org=o;
                this.UpdatePieData(org);

            }
            // updateSeattlePieChart(network);
        }
        updateSeattlePieChart(network);

        // TODO add your handling code here:
    }//GEN-LAST:event_bt_reportActionPerformed

    private void bt_viewcasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_viewcasesActionPerformed

        //chart.clear();

        updateData();
        //System.out.println("5");
        updateChart();
        //System.out.println("6");
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_viewcasesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_remove;
    private javax.swing.JButton bt_report;
    private javax.swing.JButton bt_viewcases;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_network;
    private javax.swing.JTextField txt_Name;
    // End of variables declaration//GEN-END:variables
}
