/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.sysadmin;


import java.awt.Color;
import business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;



/**
 *
 * @author heenashah
 */
public class sysadminJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    /**
     * Creates new form sysadminJPanel
     */
    public sysadminJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setDividerLocation(120);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        TopJSplitPane = new javax.swing.JPanel();
        bt_ManageNetworks = new javax.swing.JButton();
        bt_ManageEnterprises = new javax.swing.JButton();
        bt_ManageEnterpriseAdministrator = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BottomJSplitPane = new javax.swing.JPanel();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        TopJSplitPane.setBackground(new java.awt.Color(153, 204, 255));

        bt_ManageNetworks.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        bt_ManageNetworks.setText("MANAGE NETWORKS");
        bt_ManageNetworks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_ManageNetworks.setBorderPainted(false);
        bt_ManageNetworks.setContentAreaFilled(false);
        bt_ManageNetworks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ManageNetworksActionPerformed(evt);
            }
        });

        bt_ManageEnterprises.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        bt_ManageEnterprises.setText("MANAGE ENTERPRISES");
        bt_ManageEnterprises.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_ManageEnterprises.setBorderPainted(false);
        bt_ManageEnterprises.setContentAreaFilled(false);
        bt_ManageEnterprises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ManageEnterprisesActionPerformed(evt);
            }
        });

        bt_ManageEnterpriseAdministrator.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        bt_ManageEnterpriseAdministrator.setText("MANAGE ADMINSTRATORS");
        bt_ManageEnterpriseAdministrator.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_ManageEnterpriseAdministrator.setBorderPainted(false);
        bt_ManageEnterpriseAdministrator.setContentAreaFilled(false);
        bt_ManageEnterpriseAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ManageEnterpriseAdministratorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Songti SC", 1, 24)); // NOI18N
        jLabel1.setText("WELCOME SYSTEM ADMIN");

        javax.swing.GroupLayout TopJSplitPaneLayout = new javax.swing.GroupLayout(TopJSplitPane);
        TopJSplitPane.setLayout(TopJSplitPaneLayout);
        TopJSplitPaneLayout.setHorizontalGroup(
            TopJSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopJSplitPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(bt_ManageNetworks, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(bt_ManageEnterprises, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(bt_ManageEnterpriseAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(TopJSplitPaneLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TopJSplitPaneLayout.setVerticalGroup(
            TopJSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopJSplitPaneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(TopJSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ManageNetworks)
                    .addComponent(bt_ManageEnterprises)
                    .addComponent(bt_ManageEnterpriseAdministrator))
                .addGap(9, 9, 9))
        );

        jSplitPane1.setTopComponent(TopJSplitPane);

        BottomJSplitPane.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout BottomJSplitPaneLayout = new javax.swing.GroupLayout(BottomJSplitPane);
        BottomJSplitPane.setLayout(BottomJSplitPaneLayout);
        BottomJSplitPaneLayout.setHorizontalGroup(
            BottomJSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );
        BottomJSplitPaneLayout.setVerticalGroup(
            BottomJSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(BottomJSplitPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ManageNetworksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ManageNetworksActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel manageNetworkJPanel=new ManageNetworkJPanel(userProcessContainer, ecosystem);
        jSplitPane1.setBottomComponent(manageNetworkJPanel);
        /*userProcessContainer.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);*/
    }//GEN-LAST:event_bt_ManageNetworksActionPerformed

    private void bt_ManageEnterprisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ManageEnterprisesActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseJPanel manageEnterpriseJPanel=new ManageEnterpriseJPanel(userProcessContainer, ecosystem);
        jSplitPane1.setBottomComponent(manageEnterpriseJPanel);
        /*userProcessContainer.add("manageEnterpriseJPanel",manageEnterpriseJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);*/
    }//GEN-LAST:event_bt_ManageEnterprisesActionPerformed

    private void bt_ManageEnterpriseAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ManageEnterpriseAdministratorActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel=new ManageEnterpriseAdminJPanel(userProcessContainer, ecosystem);
        jSplitPane1.setBottomComponent(manageEnterpriseAdminJPanel);
        /*userProcessContainer.add("manageEnterpriseAdminJPanel",manageEnterpriseAdminJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);*/
    }//GEN-LAST:event_bt_ManageEnterpriseAdministratorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomJSplitPane;
    private javax.swing.JPanel TopJSplitPane;
    private javax.swing.JButton bt_ManageEnterpriseAdministrator;
    private javax.swing.JButton bt_ManageEnterprises;
    private javax.swing.JButton bt_ManageNetworks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
