/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.sysadmin;

import business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author heenashah
 */
public class sysadminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form sysadminJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public sysadminJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setDividerLocation(120);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblWelcomeSysAdmin = new javax.swing.JLabel();
        bt_ManageEnterprises = new javax.swing.JButton();
        bt_ManageEnterpriseAdministrator = new javax.swing.JButton();
        bt_ManageNetworks = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jCheckBox1.setText("jCheckBox1");

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setToolTipText("");
        jPanel1.setInheritsPopupMenu(true);

        lblWelcomeSysAdmin.setBackground(new java.awt.Color(0, 51, 204));
        lblWelcomeSysAdmin.setFont(new java.awt.Font("Songti SC", 1, 28)); // NOI18N
        lblWelcomeSysAdmin.setForeground(new java.awt.Color(0, 0, 204));
        lblWelcomeSysAdmin.setText("WELCOME SYSTEM ADMIN");

        bt_ManageEnterprises.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        bt_ManageEnterprises.setForeground(new java.awt.Color(0, 0, 204));
        bt_ManageEnterprises.setText("MANAGE ENTERPRISES");
        bt_ManageEnterprises.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_ManageEnterprises.setBorderPainted(false);
        bt_ManageEnterprises.setContentAreaFilled(false);
        bt_ManageEnterprises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ManageEnterprisesActionPerformed(evt);
            }
        });

        bt_ManageEnterpriseAdministrator.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        bt_ManageEnterpriseAdministrator.setForeground(new java.awt.Color(0, 0, 204));
        bt_ManageEnterpriseAdministrator.setText("MANAGE ENTERPRISE ADMINS");
        bt_ManageEnterpriseAdministrator.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_ManageEnterpriseAdministrator.setBorderPainted(false);
        bt_ManageEnterpriseAdministrator.setContentAreaFilled(false);
        bt_ManageEnterpriseAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ManageEnterpriseAdministratorActionPerformed(evt);
            }
        });

        bt_ManageNetworks.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        bt_ManageNetworks.setForeground(new java.awt.Color(0, 0, 204));
        bt_ManageNetworks.setText("MANAGE NETWORKS");
        bt_ManageNetworks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_ManageNetworks.setBorderPainted(false);
        bt_ManageNetworks.setContentAreaFilled(false);
        bt_ManageNetworks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ManageNetworksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(lblWelcomeSysAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(bt_ManageNetworks, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(bt_ManageEnterprises, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(bt_ManageEnterpriseAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblWelcomeSysAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ManageNetworks)
                    .addComponent(bt_ManageEnterprises)
                    .addComponent(bt_ManageEnterpriseAdministrator)))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ManageNetworksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ManageNetworksActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel manageNetworkJPanel=new ManageNetworkJPanel(userProcessContainer, ecosystem);
        jSplitPane1.setBottomComponent(manageNetworkJPanel);
        /*userProcessContainer.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);*/
    }//GEN-LAST:event_bt_ManageNetworksActionPerformed

    private void bt_ManageEnterprisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ManageEnterprisesActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseJPanel manageEnterpriseJPanel=new ManageEnterpriseJPanel(userProcessContainer, ecosystem);
        jSplitPane1.setBottomComponent(manageEnterpriseJPanel);
        /*userProcessContainer.add("manageEnterpriseJPanel",manageEnterpriseJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);*/
    }//GEN-LAST:event_bt_ManageEnterprisesActionPerformed

    private void bt_ManageEnterpriseAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ManageEnterpriseAdministratorActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel=new ManageEnterpriseAdminJPanel(userProcessContainer, ecosystem);
        jSplitPane1.setBottomComponent(manageEnterpriseAdminJPanel);
        /*userProcessContainer.add("manageEnterpriseAdminJPanel",manageEnterpriseAdminJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);*/
    }//GEN-LAST:event_bt_ManageEnterpriseAdministratorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ManageEnterpriseAdministrator;
    private javax.swing.JButton bt_ManageEnterprises;
    private javax.swing.JButton bt_ManageNetworks;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblWelcomeSysAdmin;
    // End of variables declaration//GEN-END:variables
}
