/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.EnterpriseAdmin;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author hetal
 */
public class EnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseAdminJPanel
     */
   JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    public EnterpriseAdminJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setDividerLocation(120);
        txtFieldEnterpriseName.setText(enterprise.getEnterpriseType().getValue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_ManageOrg = new javax.swing.JButton();
        bt_ManageEmployee = new javax.swing.JButton();
        bt_ManageEmployeeAccess = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFieldEnterpriseName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setForeground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Welcome Enterprise Admin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 198, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        bt_ManageOrg.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        bt_ManageOrg.setForeground(new java.awt.Color(51, 102, 255));
        bt_ManageOrg.setText("Manage Organization(s)");
        bt_ManageOrg.setBorderPainted(false);
        bt_ManageOrg.setContentAreaFilled(false);
        bt_ManageOrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_ManageOrgMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_ManageOrgMouseEntered(evt);
            }
        });
        bt_ManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ManageOrgActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 84, 0, 0);
        jPanel2.add(bt_ManageOrg, gridBagConstraints);

        bt_ManageEmployee.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        bt_ManageEmployee.setForeground(new java.awt.Color(51, 102, 255));
        bt_ManageEmployee.setText("Manage Employee");
        bt_ManageEmployee.setBorderPainted(false);
        bt_ManageEmployee.setContentAreaFilled(false);
        bt_ManageEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_ManageEmployeeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_ManageEmployeeMouseEntered(evt);
            }
        });
        bt_ManageEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ManageEmployeeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel2.add(bt_ManageEmployee, gridBagConstraints);

        bt_ManageEmployeeAccess.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        bt_ManageEmployeeAccess.setForeground(new java.awt.Color(51, 102, 255));
        bt_ManageEmployeeAccess.setText("Manage User");
        bt_ManageEmployeeAccess.setBorderPainted(false);
        bt_ManageEmployeeAccess.setContentAreaFilled(false);
        bt_ManageEmployeeAccess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_ManageEmployeeAccessMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_ManageEmployeeAccessMouseEntered(evt);
            }
        });
        bt_ManageEmployeeAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ManageEmployeeAccessActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 110);
        jPanel2.add(bt_ManageEmployeeAccess, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Your Enterprise is : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 218, 0, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        txtFieldEnterpriseName.setEditable(false);
        txtFieldEnterpriseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldEnterpriseNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 93;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 0, 0);
        jPanel2.add(txtFieldEnterpriseName, gridBagConstraints);

        jSplitPane1.setTopComponent(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 918, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 57, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ManageOrgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ManageOrgMouseExited
        bt_ManageOrg.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ManageOrgMouseExited

    private void bt_ManageOrgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ManageOrgMouseEntered
        bt_ManageOrg.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ManageOrgMouseEntered

    private void bt_ManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ManageOrgActionPerformed
        ManageOrganizationsJPanel manageorganizationsJPanel=new ManageOrganizationsJPanel(userProcessContainer,enterprise, system,enterprise.getOrganizationDirectory());
        jSplitPane1.setBottomComponent(manageorganizationsJPanel);
    }//GEN-LAST:event_bt_ManageOrgActionPerformed

    private void bt_ManageEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ManageEmployeeMouseExited
        bt_ManageEmployee.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ManageEmployeeMouseExited

    private void bt_ManageEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ManageEmployeeMouseEntered
        bt_ManageEmployee.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ManageEmployeeMouseEntered

    private void bt_ManageEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ManageEmployeeActionPerformed
        ManageEmployeeJPanel manageemployeeJPanel=new ManageEmployeeJPanel(userProcessContainer,enterprise, system,enterprise.getOrganizationDirectory());
        jSplitPane1.setBottomComponent(manageemployeeJPanel);
    }//GEN-LAST:event_bt_ManageEmployeeActionPerformed

    private void bt_ManageEmployeeAccessMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ManageEmployeeAccessMouseExited
        bt_ManageEmployeeAccess.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ManageEmployeeAccessMouseExited

    private void bt_ManageEmployeeAccessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ManageEmployeeAccessMouseEntered
        bt_ManageEmployeeAccess.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ManageEmployeeAccessMouseEntered

    private void bt_ManageEmployeeAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ManageEmployeeAccessActionPerformed
        ManageUsersJPanel manageuserJPanel=new ManageUsersJPanel(userProcessContainer,enterprise, system);
        jSplitPane1.setBottomComponent(manageuserJPanel);
    }//GEN-LAST:event_bt_ManageEmployeeAccessActionPerformed

    private void txtFieldEnterpriseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEnterpriseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEnterpriseNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ManageEmployee;
    private javax.swing.JButton bt_ManageEmployeeAccess;
    private javax.swing.JButton bt_ManageOrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField txtFieldEnterpriseName;
    // End of variables declaration//GEN-END:variables
}
