/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.EnterpriseAdmin;
import business.EcoSystem;
import business.Employee.Employee;
import business.Enterprise.Enterprise;
import business.Organization.Organization;
import business.Organization.OrganizationDirectory;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hetal
 */
public class ManageEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmployeeJPanel
     */
       JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    private OrganizationDirectory organizationDir;
    
    public ManageEmployeeJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system,OrganizationDirectory organizationDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.organizationDir = organizationDir;
        
        populateOrganizationComboBox();
        populateOrganizationEmpComboBox();
        
    }
     public void populateOrganizationComboBox(){
        cb_org.removeAllItems();
        
        for (Organization organization : organizationDir.getOrganizationList()){
            cb_org.addItem(organization);
        }
    }
    
    public void populateOrganizationEmpComboBox(){
        cb_org.removeAllItems();
        
        for (Organization organization : organizationDir.getOrganizationList()){
            cb_org.addItem(organization);
        }
    }

    private void populateTable(Organization organization){
        DefaultTableModel model = (DefaultTableModel) tableOrg.getModel();
        
        model.setRowCount(0);
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[1];
            //row[0] = employee.getId();
            row[0] = employee;
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrg = new javax.swing.JTable();
        lblSelectOrg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        bt_CreateEmployee = new javax.swing.JButton();
        cb_org = new javax.swing.JComboBox();
        bt_Delete = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Songti SC", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE EMPLOYEE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 671, 37));

        tableOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableOrg);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 220, 100));

        lblSelectOrg.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        lblSelectOrg.setForeground(new java.awt.Color(0, 0, 204));
        lblSelectOrg.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSelectOrg.setText("ORGANIZATION");
        jPanel2.add(lblSelectOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, 180, 20));

        jLabel3.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("NAME");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 139, 22));

        txt_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, -1));

        bt_CreateEmployee.setBackground(new java.awt.Color(0, 0, 204));
        bt_CreateEmployee.setFont(new java.awt.Font("Songti SC", 1, 14)); // NOI18N
        bt_CreateEmployee.setForeground(new java.awt.Color(255, 255, 255));
        bt_CreateEmployee.setText("CREATE EMPLOYEE");
        bt_CreateEmployee.setBorderPainted(false);
        bt_CreateEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_CreateEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_CreateEmployeeMouseExited(evt);
            }
        });
        bt_CreateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CreateEmployeeActionPerformed(evt);
            }
        });
        jPanel2.add(bt_CreateEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        cb_org.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_org.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_orgActionPerformed(evt);
            }
        });
        jPanel2.add(cb_org, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 120, 20));

        bt_Delete.setBackground(new java.awt.Color(0, 0, 204));
        bt_Delete.setFont(new java.awt.Font("Songti SC", 1, 14)); // NOI18N
        bt_Delete.setForeground(new java.awt.Color(255, 255, 255));
        bt_Delete.setText("DELETE EMPLOYEE");
        bt_Delete.setBorderPainted(false);
        bt_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_DeleteMouseExited(evt);
            }
        });
        bt_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_DeleteActionPerformed(evt);
            }
        });
        jPanel2.add(bt_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NameActionPerformed

    private void bt_CreateEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CreateEmployeeMouseExited
        bt_CreateEmployee.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_CreateEmployeeMouseExited

    private void bt_CreateEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CreateEmployeeMouseEntered
        bt_CreateEmployee.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_bt_CreateEmployeeMouseEntered

    private void bt_CreateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CreateEmployeeActionPerformed
        // TODO add your handling code here:

        if( txt_Name.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "please enter all mandatory fields");
            return;
        }
        Organization organization = (Organization) cb_org.getSelectedItem();
        String name = txt_Name.getText();
        // String email="";
        organization.getEmployeeDirectory().createEmployee(name);
        populateTable(organization);
        txt_Name.setText("");
    }//GEN-LAST:event_bt_CreateEmployeeActionPerformed

    private void cb_orgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_orgActionPerformed
        // TODO add your handling code here:
        Organization organization = (Organization) cb_org.getSelectedItem();
        if (organization != null){
            populateTable(organization);
        }
    }//GEN-LAST:event_cb_orgActionPerformed

    private void bt_DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_DeleteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_DeleteMouseExited

    private void bt_DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_DeleteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_DeleteMouseEntered

    private void bt_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_DeleteActionPerformed
        // TODO add your handling code here:
        Organization organization = (Organization) cb_org.getSelectedItem();
        int selectedRow = tableOrg.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select the row to delete the account", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            Employee e = (Employee) tableOrg.getValueAt(selectedRow, 0);

            for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
                if (e==employee){
                    organization.getEmployeeDirectory().getEmployeeList().remove(e);
                    break;
                }
            }
            JOptionPane.showMessageDialog(null, "You have successfully deleted the account");
            populateTable(organization);
        }
    }//GEN-LAST:event_bt_DeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_CreateEmployee;
    private javax.swing.JButton bt_Delete;
    private javax.swing.JComboBox cb_org;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelectOrg;
    private javax.swing.JTable tableOrg;
    private javax.swing.JTextField txt_Name;
    // End of variables declaration//GEN-END:variables
}
