/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Psychiatrist;
import business.EcoSystem;
import business.Network.Network;
import business.Organization.CaseReporterOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.CaseReporterWorkRequest;
import business.WorkQueue.PsychiatristWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hetal
 */
public class PsychiatristRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PsychiatristRequestJPanel
     */
     JPanel userProcessContainer;
    EcoSystem system;
    UserAccount userAccount;
    Organization organization;
    PsychiatristWorkRequest request;
    Network network;
    public PsychiatristRequestJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount userAccount,Organization organization,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.organization= organization;
        this.userAccount = userAccount;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_PsychiatrisDetails = new javax.swing.JTable();
        bt_AssignRequest = new javax.swing.JButton();
        bt_Encounters = new javax.swing.JButton();
        bt_CaseComplete = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        lblHeader.setFont(new java.awt.Font("Songti SC", 1, 28)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(0, 0, 204));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("MANAGE REQUESTS");

        tb_PsychiatrisDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "TYPE", "STATUS", "ASSIGNED TO "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_PsychiatrisDetails);

        bt_AssignRequest.setBackground(new java.awt.Color(0, 0, 204));
        bt_AssignRequest.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        bt_AssignRequest.setForeground(new java.awt.Color(255, 255, 255));
        bt_AssignRequest.setText("ASSIGN REQUEST");
        bt_AssignRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_AssignRequestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_AssignRequestMouseExited(evt);
            }
        });
        bt_AssignRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AssignRequestActionPerformed(evt);
            }
        });

        bt_Encounters.setBackground(new java.awt.Color(0, 0, 204));
        bt_Encounters.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        bt_Encounters.setForeground(new java.awt.Color(255, 255, 255));
        bt_Encounters.setText("ENCOUNTERS");
        bt_Encounters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EncountersActionPerformed(evt);
            }
        });

        bt_CaseComplete.setBackground(new java.awt.Color(0, 0, 204));
        bt_CaseComplete.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        bt_CaseComplete.setForeground(new java.awt.Color(255, 255, 255));
        bt_CaseComplete.setText("CASE COMPLETE");
        bt_CaseComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CaseCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_AssignRequest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_Encounters, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_CaseComplete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblHeader)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(bt_AssignRequest)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Encounters)
                        .addGap(18, 18, 18)
                        .addComponent(bt_CaseComplete))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_AssignRequestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AssignRequestMouseEntered
        bt_AssignRequest.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_bt_AssignRequestMouseEntered

    private void bt_AssignRequestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AssignRequestMouseExited
        bt_AssignRequest.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_AssignRequestMouseExited

    private void bt_AssignRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AssignRequestActionPerformed

        int selectedRow = tb_PsychiatrisDetails.getSelectedRow();
        PsychiatristWorkRequest request = (PsychiatristWorkRequest)tb_PsychiatrisDetails.getValueAt(selectedRow, 2);
        if (CheckOpenCases(userAccount) == 0){
            request.setReceiver(userAccount);
            request.setStatus("Accepted");
            populateTable();
            sendInvite(request);
        }else
        {
            JOptionPane.showMessageDialog(null, "Only one case can be accepted at a time");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_bt_AssignRequestActionPerformed

    private void bt_EncountersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EncountersActionPerformed

        int selectedRow = tb_PsychiatrisDetails.getSelectedRow();

        DefaultTableModel model=(DefaultTableModel) tb_PsychiatrisDetails.getModel();
        String s= tb_PsychiatrisDetails.getValueAt(selectedRow, 2).toString();
        String status="Waiting";
        if(status.equalsIgnoreCase(s))
        {
            JOptionPane.showMessageDialog(null, "Access Denied");
        }
        else{
            if (selectedRow < 0){
                return;
            }
            PsychiatristWorkRequest request = (PsychiatristWorkRequest)tb_PsychiatrisDetails.getValueAt(selectedRow, 2);

            if (request.getReceiver()!=userAccount){
                JOptionPane.showMessageDialog(this, "You cannot view the report of this case. Access Denied.");
            }else{
                PsychiatristEncounterJPanel lencounterJPanel = new PsychiatristEncounterJPanel(userProcessContainer,system,userAccount,network,organization,request);
                userProcessContainer.add("caseReportJPanel", lencounterJPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_EncountersActionPerformed

    private void bt_CaseCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CaseCompleteActionPerformed
        int selectedRow = tb_PsychiatrisDetails.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        WorkRequest request = (PsychiatristWorkRequest)tb_PsychiatrisDetails.getValueAt(selectedRow, 2);
        request.setReceiver(userAccount);
        request.setStatus("Case Completed");
        populateTable();
    }//GEN-LAST:event_bt_CaseCompleteActionPerformed
private void populateTable() {
        DefaultTableModel model= (DefaultTableModel) tb_PsychiatrisDetails.getModel();
        Object[] row=new Object[4];
        model.setRowCount(0);
        
         for(PsychiatristWorkRequest request : organization.getWorkQueue().getPsychiatristWorkRequestList())
         {
         
            row[0]=request.getCaseReporterWorkRequest().getUserName();
            row[1] = request.getCaseReporterWorkRequest().getAssaultType();
            row[2] = request;
            if (request.getReceiver()==null){
              row[3] = "Not Assigned";
            }else{
              row[3] = request.getReceiver();
            }
            model.addRow(row);
        }
    }

    private void sendInvite(PsychiatristWorkRequest request) {
        String FromEmail="sexualawareness.help@gmail.com";
        String FromEmailPass="Fin@lProject21";
        String Subject = "Sign up successful";
        
        Properties properties=new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");
        
        Session session=Session.getDefaultInstance(properties, new javax.mail.Authenticator(){
           @Override
            protected PasswordAuthentication getPasswordAuthentication(){
         return new PasswordAuthentication(FromEmail,FromEmailPass);
        }
        });
        
        try
        {
            Message msg=new MimeMessage(session);
            msg.setFrom(new InternetAddress(FromEmail));
            msg.addRecipients(Message.RecipientType.TO, InternetAddress.parse(request.getCaseReporterWorkRequest().getEmail()));
            msg.setSubject("Invitation for a session with Help Provider.");
            msg.setText("Dear "+ request.getCaseReporterWorkRequest().getUserName()+"\n"+"I am here to help you. Join me through the following link for the next encounter."+"\n"+"zoom1.link"+"\n"+"Best,"+"\n"+userAccount.getEmp().getName());
            Transport.send(msg);
            JOptionPane.showMessageDialog(this, "Invitation has been sent successfully.");

        }catch(Exception e)
        {
            System.out.println(""+e);
            //JOptionPane.showMessageDialog(this, "Incorrect E-mail id.Invitation cannot be been sent.");

        }
    }
    
    private int CheckOpenCases(UserAccount userAccount) {
        int a = 0;
        for(PsychiatristWorkRequest request : organization.getWorkQueue().getPsychiatristWorkRequestList())
        {
        
          if (request.getReceiver()==userAccount){
              if (request.getStatus().equalsIgnoreCase("Accepted")){
                  a = a + 1;
              }
          } 
        }
        return a; 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_AssignRequest;
    private javax.swing.JButton bt_CaseComplete;
    private javax.swing.JButton bt_Encounters;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTable tb_PsychiatrisDetails;
    // End of variables declaration//GEN-END:variables
}
