/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CaseReporter;


import buisness.Enterprise.CaseReporterEnterprise;
import buisness.Enterprise.Enterprise;
import business.Network.Network;
import buisness.Organization.CaseReporterOrganization;
import buisness.Organization.Organization;
import business.UserAccount.UserAccount;
import business.EcoSystem;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author vishwa
 */
public class CaseReporter extends javax.swing.JPanel {

    /**
     * Creates new form CaseReporter
     */
     private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private CaseReporterOrganization HSOrganization; 
    private CaseReporterEnterprise HSenterprise;
    private EcoSystem system;
    private Network network;
    
    public CaseReporter(JPanel userProcessContainer, UserAccount account, Organization organization,Enterprise enterprise,EcoSystem business,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.HSOrganization = (CaseReporterOrganization) organization;
        this.HSenterprise = (CaseReporterEnterprise) enterprise;
        this.network = network;
      
  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jVolunteerSplitPanel = new javax.swing.JSplitPane();
        jPanel09 = new javax.swing.JPanel();
        lblCaseReporter = new javax.swing.JLabel();
        btnViewStatus = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jVolunteerSplitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel09.setBackground(new java.awt.Color(153, 204, 255));

        lblCaseReporter.setFont(new java.awt.Font("Songti SC", 1, 36)); // NOI18N
        lblCaseReporter.setForeground(new java.awt.Color(61, 64, 91));
        lblCaseReporter.setText("Welcome Case Reporter");

        btnViewStatus.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        btnViewStatus.setForeground(new java.awt.Color(61, 64, 91));
        btnViewStatus.setText("View Status");
        btnViewStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewStatus.setBorderPainted(false);
        btnViewStatus.setContentAreaFilled(false);
        btnViewStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewStatusMouseExited(evt);
            }
        });
        btnViewStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStatusActionPerformed(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        btnReport.setForeground(new java.awt.Color(61, 64, 91));
        btnReport.setText("Report");
        btnReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReport.setBorderPainted(false);
        btnReport.setContentAreaFilled(false);
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel09Layout = new javax.swing.GroupLayout(jPanel09);
        jPanel09.setLayout(jPanel09Layout);
        jPanel09Layout.setHorizontalGroup(
            jPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel09Layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(lblCaseReporter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnViewStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel09Layout.setVerticalGroup(
            jPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel09Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lblCaseReporter)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel09Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel09Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewStatus)
                    .addComponent(btnReport))
                .addGap(19, 19, 19))
        );

        jVolunteerSplitPanel.setTopComponent(jPanel09);

        jPanel10.setBackground(new java.awt.Color(153, 204, 255));
        jPanel10.setLayout(new java.awt.GridBagLayout());
        jVolunteerSplitPanel.setRightComponent(jPanel10);

        jPanel8.add(jVolunteerSplitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 0, 1110, 530));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 530));

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -5, 1110, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewStatusMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewStatusMouseEntered

    private void btnViewStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewStatusMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewStatusMouseExited

    private void btnViewStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStatusActionPerformed
        // TODO add your handling code here:
        CaseReporterViewStatusJPanel reportJPanel1=new CaseReporterViewStatusJPanel(userProcessContainer,userAccount,HSOrganisation,HSenterprise,business);
        jVolunteerSplitPanel.setBottomComponent(reportJPanel1);
    }//GEN-LAST:event_btnViewStatusActionPerformed

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        btnReport.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
        btnReport.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportMouseExited

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        ReportJPanel reportJPanel=new ReportJPanel(userProcessContainer,business,userAccount,HSOrganisation,network);
        jVolunteerSplitPanel.setBottomComponent(reportJPanel);
        //ReportJFrame r = new ReportJFrame(system,network,ua,org);
    }//GEN-LAST:event_btnReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnViewStatus;
    private javax.swing.JPanel jPanel09;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSplitPane jVolunteerSplitPanel;
    private javax.swing.JLabel lblCaseReporter;
    // End of variables declaration//GEN-END:variables
}
