/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CaseReporter;

import business.EcoSystem;
import business.Enterprise.CaseReporterEnterprise;
import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.CaseReporterOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author hetal
 */
public class CaseReporter extends javax.swing.JPanel {

    /**
     * Creates new form CaseReporter
     */
     private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private CaseReporterOrganization HSOrganization; 
    private CaseReporterEnterprise HSenterprise;
    private EcoSystem system;
    private Network network;
    
    public CaseReporter(JPanel userProcessContainer, UserAccount account, Organization organization,Enterprise enterprise,EcoSystem business,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.HSOrganization = (CaseReporterOrganization) organization;
        this.HSenterprise = (CaseReporterEnterprise) enterprise;
        this.network = network;
      
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jVolunteerSplitPanel = new javax.swing.JSplitPane();
        jPanel09 = new javax.swing.JPanel();
        lblCaseReporter = new javax.swing.JLabel();
        bt_ViewStatus = new javax.swing.JButton();
        bt_Report = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jVolunteerSplitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel09.setBackground(new java.awt.Color(204, 204, 255));
        jPanel09.setLayout(new java.awt.GridBagLayout());

        lblCaseReporter.setFont(new java.awt.Font("Songti SC", 1, 28)); // NOI18N
        lblCaseReporter.setForeground(new java.awt.Color(0, 0, 204));
        lblCaseReporter.setText("WELCOME CASE REPORTER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 112, 0, 0);
        jPanel09.add(lblCaseReporter, gridBagConstraints);

        bt_ViewStatus.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        bt_ViewStatus.setForeground(new java.awt.Color(0, 0, 204));
        bt_ViewStatus.setText("VIEW STATUS");
        bt_ViewStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_ViewStatus.setBorderPainted(false);
        bt_ViewStatus.setContentAreaFilled(false);
        bt_ViewStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_ViewStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_ViewStatusMouseExited(evt);
            }
        });
        bt_ViewStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ViewStatusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 47, 11, 84);
        jPanel09.add(bt_ViewStatus, gridBagConstraints);

        bt_Report.setFont(new java.awt.Font("Songti SC", 1, 18)); // NOI18N
        bt_Report.setForeground(new java.awt.Color(0, 0, 204));
        bt_Report.setText("REPORT");
        bt_Report.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_Report.setBorderPainted(false);
        bt_Report.setContentAreaFilled(false);
        bt_Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_ReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_ReportMouseExited(evt);
            }
        });
        bt_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ReportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 57;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 74, 11, 0);
        jPanel09.add(bt_Report, gridBagConstraints);

        jVolunteerSplitPanel.setTopComponent(jPanel09);

        jPanel10.setBackground(new java.awt.Color(153, 204, 255));
        jPanel10.setLayout(new java.awt.GridBagLayout());
        jVolunteerSplitPanel.setRightComponent(jPanel10);

        jPanel8.add(jVolunteerSplitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 0, 1110, 530));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 530));

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -5, 1110, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ViewStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ViewStatusMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ViewStatusMouseEntered

    private void bt_ViewStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ViewStatusMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ViewStatusMouseExited

    private void bt_ViewStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ViewStatusActionPerformed
        // TODO add your handling code here:
        CaseReporterViewStatusJPanel reportJPanel1=new CaseReporterViewStatusJPanel(userProcessContainer,userAccount,HSOrganization,HSenterprise,business);
        jVolunteerSplitPanel.setBottomComponent(reportJPanel1);
    }//GEN-LAST:event_bt_ViewStatusActionPerformed

    private void bt_ReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ReportMouseEntered
        bt_Report.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ReportMouseEntered

    private void bt_ReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ReportMouseExited
        bt_Report.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ReportMouseExited

    private void bt_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ReportActionPerformed
        ReportJPanel reportJPanel=new ReportJPanel(userProcessContainer,business,userAccount,HSOrganization,network);
        jVolunteerSplitPanel.setBottomComponent(reportJPanel);
        //ReportJFrame r = new ReportJFrame(system,network,ua,org);
    }//GEN-LAST:event_bt_ReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Report;
    private javax.swing.JButton bt_ViewStatus;
    private javax.swing.JPanel jPanel09;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSplitPane jVolunteerSplitPanel;
    private javax.swing.JLabel lblCaseReporter;
    // End of variables declaration//GEN-END:variables
}
